name: Vérification des tests

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer les dépendances Node.js
        run: npm install
        working-directory: front
      - name: Exécuter les tests
        run: npm run test
        working-directory: front
      - name: Installer les dépendances Node.js
        run: npm install
        working-directory: back
      - name: Exécuter les tests
        run: npm run test
        working-directory: back
